DSC/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DSC.Models;

namespace DSC.Controllers
{
    public class CompanyController : Controller
    {
        public IActionResult Company()
        {
            ViewData["Message"] = "Company.";
            return View();
        }

        public IActionResult IdealNews()
        {
            ViewData["Message"] = "IdealNews.";

            return View();
        }

        public IActionResult UnrepeatableBeauty()
        {
            ViewData["Message"] = "UnrepeatableBeauty.";

            return View();
        }

        public IActionResult Contacts()
        {
            ViewData["Message"] = "Contacts.";
            return View();
        }
        
        public IActionResult SocialWall()
        {
            ViewData["Message"] = "SocialWall.";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSC/Controllers/IndoorApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DSC.Models;

namespace DSC.Controllers
{
    public class IndoorApplicationsController : Controller
    {
        public IActionResult bathroom()
        {
            ViewData["Message"] = "bathroom";
            return View();
        }
        public IActionResult bedrooms()
        {
            ViewData["Message"] = "bedrooms";
            return View();
        }
        public IActionResult feed()
        {
            ViewData["Message"] = "feed";
            return View();
        }
        public IActionResult furniture()
        {
            ViewData["Message"] = "furniture";
            return View();
        }
        public IActionResult kitchen()
        {
            ViewData["Message"] = "kitchen";
            return View();
        }
        public IActionResult living()
        {
            ViewData["Message"] = "living";
            return View();
        }
        public IActionResult museums()
        {
            ViewData["Message"] = "museums";
            return View();
        }
        public IActionResult offices()
        {
            ViewData["Message"] = "offices";
            return View();
        }
        public IActionResult publicplaces()
        {
            ViewData["Message"] = "publicplaces";
            return View();
        }
        public IActionResult restaurant()
        {
            ViewData["Message"] = "restaurant";
            return View();
        }
        public IActionResult retail()
        {
            ViewData["Message"] = "retail";
            return View();
        }
        public IActionResult staircases()
        {
            ViewData["Message"] = "staircases";
            return View();
        }
        public IActionResult walls()
        {
            ViewData["Message"] = "walls";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSC/Controllers/OutdoorApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DSC.Models;

namespace DSC.Controllers
{
    public class OutdoorApplicationsController : Controller
    {
        public IActionResult amusementparks()
        {
            ViewData["Message"] = "amusementparks";
            return View();
        }
        public IActionResult carparks()
        {
            ViewData["Message"] = "carparks";
            return View();
        }
        public IActionResult feed()
        {
            ViewData["Message"] = "feed";
            return View();
        }
        public IActionResult outdoorliving()
        {
            ViewData["Message"] = "outdoorliving";
            return View();
        }
        public IActionResult publicareas()
        {
            ViewData["Message"] = "publicareas";
            return View();
        }
        public IActionResult ramps()
        {
            ViewData["Message"] = "ramps";
            return View();
        }
        public IActionResult squares()
        {
            ViewData["Message"] = "squares";
            return View();
        }
        public IActionResult swimmingpools()
        {
            ViewData["Message"] = "swimmingpools";
            return View();
        }
        public IActionResult walkways()
        {
            ViewData["Message"] = "walkways";
            return View();
        }
        public IActionResult walls()
        {
            ViewData["Message"] = "walls";
            return View();
        }
       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSC/Controllers/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DSC.Models;

namespace DSC.Controllers
{
    public class SolutionsController : Controller
    {
        public IActionResult Typologies()
        {
            ViewData["Message"] = "Typologies.";
            return View();
        }

        public IActionResult IndoorApplications()
        {
            ViewData["Message"] = "IndoorApplications.";

            return View();
        }

        public IActionResult OutdoorApplications()
        {
            ViewData["Message"] = "OutdoorApplications.";

            return View();
        }

        public IActionResult Styles()
        {
            ViewData["Message"] = "Styles.";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSC/Controllers/StylesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DSC.Models;

namespace DSC.Controllers
{
    public class StylesController : Controller
    {
        public IActionResult classicalcontemporary()
        {
            ViewData["Message"] = "classicalcontemporary";
            return View();
        }
        public IActionResult colourful()
        {
            ViewData["Message"] = "colourful";
            return View();
        }
        public IActionResult eclectic()
        {
            ViewData["Message"] = "eclectic";
            return View();
        }
        public IActionResult feed()
        {
            ViewData["Message"] = "feed";
            return View();
        }
        public IActionResult industrial()
        {
            ViewData["Message"] = "industrial";
            return View();
        }
        public IActionResult minimal()
        {
            ViewData["Message"] = "minimal";
            return View();
        }
       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DSC/Views/Solutions/IndoorApplications.cshtml
@{
    ViewData["Title"] = "IndoorApplications";
}
    <body class="archive post-type-archive post-type-archive-indoor-application">

        <div id="stickyTrigger"></div>
        <div class="wrap container-fluid" role="document">
            <div class="content row">
                <main class="main">

                    <section class="boxed-slider-hero">
                        <div class="text-container">
                            <div class="page-header">

                                <div class="breadcrumbs-container">
                                    <p id="breadcrumbs">
                                    <span xmlns:v="http://rdf.data-vocabulary.org/#">
                                        <span typeof="v:Breadcrumb">
                                            <a asp-area="" asp-controller="Home" asp-action="Index" rel="v:url" property="v:title">Home</a>
                                            / <span class="breadcrumb_last">Indoor Applications</span>
                                        </span></span></p>
                                </div>

                                <div class="page-title-container">
                                    <h1>Indoor Applications</h1>
                                </div>

                                <div class="page-subtitle">
                                    <p class="text-1">
                                        Shape and create the environment you want among the many Ideal Work® solutions.<br />
                                        Choose your custom-made coating.
                                    </p>
                                </div>

                            </div>


                            <div class="show-more">
                                <a href="#more" class="hidden-xs hidden-sm">
                                    <span class="icon icon-arrow-down"></span>
                                    <span class="text-3">
                                        Find out more
                                    </span>
                                </a>
                            </div>
                        </div>

                        <div class="cover-holder" style="background-image: url('../wp-content/uploads/2017/07/indoor.jpg')">
                            <div class="slider-overlay"></div>
                        </div>



                    </section>


                    <div class="container">
                        <div id="more" class="clearfix listing-items-row">
                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="living">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/Living-idealwork.jpg')">
                                    </div>
                                    <h5>Living</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="bathroom">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/Slider-bathroom.jpg')">
                                    </div>
                                    <h5>Bathroom</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="bedrooms">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/07/WP_ArjaanDeFeyter_Kanaal_014klein-1.jpg')">
                                    </div>
                                    <h5>Bedrooms</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="kitchen">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2019/03/2019_02_LEDOUX-%e2%80%93-HELLEPUTTE_belgio_MT_45.jpg')">
                                    </div>
                                    <h5>Kitchen</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="restaurant">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/reastaurant-idealwork-architop-5-quadrato.jpg')">
                                    </div>
                                    <h5>Restaurant</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="walls">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/07/annashowroom.jpg')">
                                    </div>
                                    <h5>Walls</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="staircases">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/solution-listing-scale.jpg')">
                                    </div>
                                    <h5>Staircases</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="furniture">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/solution-listing-mobili.jpg')">
                                    </div>
                                    <h5>Furniture</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="museums">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/solution-listing-musei.jpg')">
                                    </div>
                                    <h5>Museums</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="offices">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/11/2017_08_Smart-Office-Dubai_-MT7_web.jpg')">
                                    </div>
                                    <h5>Offices</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="retail">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/solution-listing-negozi.jpg')">
                                    </div>
                                    <h5>Retail</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="IndoorApplications" asp-action="publicplaces">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/solution-listing-luoghi-pubblici.jpg')">
                                    </div>
                                    <h5>Public Places</h5>
                                </a>
                            </div>


                        </div>
                    </div>

                </main><!-- /.main -->
            </div><!-- /.content -->

            <div class="prefooter container">
                <div class="row">
                    <div class="cta-title-container col-md-6">
                        <h3>Contact Us</h3>
                    </div>

                    <div class="cta-container col-md-4">
                        <p class="text-1">
                            Do you have any other requests or curiosities?<br />
                            Do you want more information about products and services?<br />
                            You want to become an Ideal Work® partner<br />
                            or simply contact the company?
                        </p>
                        <a asp-area="" asp-controller="Company" asp-action="Contacts" class="cta">
                            <span class="icon icon-arrow-right-small"></span>
                            <span class="text-3">Contact Us</span>
                        </a>
                    </div>
                </div>
            </div>
        </div><!-- /.wrap -->

    </body>

DSC/Views/Solutions/OutdoorApplications.cshtml
@{
    ViewData["Title"] = "OutdoorApplications";
}
    <body class="archive post-type-archive post-type-archive-outdoor-application">

        <div id="stickyTrigger"></div>
        <div class="wrap container-fluid" role="document">
            <div class="content row">
                <main class="main">

                    <section class="boxed-slider-hero">
                        <div class="text-container">
                            <div class="page-header">

                                <div class="breadcrumbs-container">
                                    <p id="breadcrumbs">
                                        <span xmlns:v="http://rdf.data-vocabulary.org/#">
                                            <span typeof="v:Breadcrumb">
                                                <a asp-area="" asp-controller="Home" asp-action="Index" rel="v:url" property="v:title">Home</a>
                                                / <span class="breadcrumb_last">Outdoor Applications</span>
                                            </span>
                                        </span>
                                    </p>
                                </div>

                                <div class="page-title-container">
                                    <h1>Outdoor Applications</h1>
                                </div>

                                <div class="page-subtitle">
                                    <p class="text-1">Find the ideal, long-lasting solution for outdoors, with no thickness or weight limits. Choose the material and shape you like</p>
                                </div>

                            </div>


                            <div class="show-more">
                                <a href="#more" class="hidden-xs hidden-sm">
                                    <span class="icon icon-arrow-down"></span>
                                    <span class="text-3">
                                        Find out more
                                    </span>
                                </a>
                            </div>
                        </div>

                        <div class="cover-holder" style="background-image: url('../wp-content/uploads/2017/07/outdoor.jpg')">
                            <div class="slider-overlay"></div>
                        </div>



                    </section>


                    <div class="container">
                        <div id="more" class="clearfix listing-items-row">
                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="publicareas">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_aree_pubbliche.jpg')">
                                    </div>
                                    <h5>Public Areas</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="outdoorliving">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/08/living-esterno.jpg')">
                                    </div>
                                    <h5>Outdoor Living</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="squares">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_piazze.jpg')">
                                    </div>
                                    <h5>Squares</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="walkways">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_camminamenti.jpg')">
                                    </div>
                                    <h5>Walkways</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="carparks">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_parcheggi.jpg')">
                                    </div>
                                    <h5>Car Parks</h5>
                                </a>
                            </div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="swimmingpools">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_piscine.jpg')">
                                    </div>
                                    <h5>Swimming Pools</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="ramps">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_rampe.jpg')">
                                    </div>
                                    <h5>Ramps</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="amusementparks">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/06/appoutdoor_parchi_divertimento2.jpg')">
                                    </div>
                                    <h5>Amusement Parks</h5>
                                </a>
                            </div>

                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="OutdoorApplications" asp-action="walls">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/appoutdoor_muro_stampato.jpg')">
                                    </div>
                                    <h5>Walls</h5>
                                </a>
                            </div>


                        </div>
                    </div>

                </main><!-- /.main -->
            </div><!-- /.content -->
            <div class="prefooter container">
                <div class="row">
                    <div class="cta-title-container col-md-6">
                        <h3>Contact Us</h3>
                    </div>

                    <div class="cta-container col-md-4">
                        <p class="text-1">
                            Do you have any other requests or curiosities?<br />
                            Do you want more information about products and services?<br />
                            You want to become an Ideal Work® partner<br />
                            or simply contact the company?
                        </p>
                        <a asp-area="" asp-controller="Company" asp-action="Contacts" class="cta">
                            <span class="icon icon-arrow-right-small"></span>
                            <span class="text-3">Contact Us</span>
                        </a>
                    </div>
                </div>
            </div>
        </div><!-- /.wrap -->
    </body>

DSC/Views/Solutions/Typologies.cshtml
@{
    ViewData["Title"] = "Typologies";
}
    <body class="archive post-type-archive post-type-archive-typology">
        <div id="stickyTrigger"></div>
        <div class="wrap container-fluid" role="document">
            <div class="content row">
                <main class="main">

                    <section class="boxed-slider-hero">
                        <div class="text-container">
                            <div class="page-header">

                                <div class="breadcrumbs-container">
                                    <p id="breadcrumbs"><span xmlns:v="http://rdf.data-vocabulary.org/#">
                                        <span typeof="v:Breadcrumb">
                                            <a asp-area="" asp-controller="Home" asp-action="Index" rel="v:url" property="v:title">Home</a> 
                                        / <span class="breadcrumb_last">Typologies</span></span></span></p>
                                </div>

                                <div class="page-title-container">
                                    <h1>Typologies</h1>
                                </div>

                                <div class="page-subtitle">
                                    <p class="text-1">Typical Applications</p>
                                </div>

                            </div>


                            <div class="show-more">
                                <a href="#more" class="hidden-xs hidden-sm">
                                    <span class="icon icon-arrow-down"></span>
                                    <span class="text-3">
                                        Find out more
                                    </span>
                                </a>
                            </div>
                        </div>

                        <div class="cover-holder" style="background-image: url('../wp-content/uploads/2017/07/tipologie.jpg')">
                            <div class="slider-overlay"></div>
                        </div>



                    </section>


                    <div class="container">
                        <div id="more" class="clearfix listing-items-row">
                            <div class="listing-item listing-item-big">
                                <a asp-area="" asp-controller="Typologies" asp-action="floors">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/tipo_pavimenti.jpg')">
                                    </div>
                                    <h5>Floors</h5>
                                </a>
</div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="Typologies" asp-action="coatings">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/tipo_rivestimenti.jpg')">
                                    </div>
                                    <h5>Coatings</h5>
                                </a>
</div>

                            <div class="listing-item">
                                <a asp-area="" asp-controller="Typologies" asp-action="flooringcoatings">
                                    <div class="image-holder" style="background-image: url('../wp-content/uploads/2017/05/tipo_pavimenti_e_rivestimenti.jpg')">
                                    </div>
                                    <h5>Flooring &#038; Coatings</h5>
                                </a>
                            </div>


                        </div>
                    </div>

                </main><!-- /.main -->
            </div><!-- /.content -->

            <div class="prefooter container">
                <div class="row">
                    <div class="cta-title-container col-md-6">
                        <h3>Contact Us</h3>
                    </div>

                    <div class="cta-container col-md-4">
                        <p class="text-1">
                            Do you have any other requests or curiosities?<br />
                            Do you want more information about products and services?<br />
                            You want to become an Ideal Work® partner<br />
                            or simply contact the company?
                        </p>
                        <a asp-area="" asp-controller="Company" asp-action="Contacts" class="cta">
                            <span class="icon icon-arrow-right-small"></span>
                            <span class="text-3">Contact Us</span>
                        </a>
                    </div>
                </div>
            </div>
        </div><!-- /.wrap -->
    </body>